### ISSUE TITLE
MODiX website crashes on certain devices (iPhones?) on iOS.

### ISSUE THREAD

**Issue by calledude** [discord-csharp/MODiX#302] opened 2019-02-21 18:18 UTC
Upon visiting http://mod.gg/ safari either crashes or reloads until safari spits out an error saying that a problem repeatedly occurred on the website.

The problem is confirmed on iOS12.1.4 and iOS11.3.1

![vlc_2019-02-21_18-56-56](https://user-images.githubusercontent.com/22471295/53190843-c1c50c00-360a-11e9-8d71-42bd6d8c10f4.png)

The issue cannot be reproduced on iPads on various versions (iOS 11, 12.0.1, 12.1) which indicates that this might be isolated to iPhones.

**Comment by hizamakura** [comment] 2019-08-23 13:50
Confirmed to crash on both Safari and Google Chrome on iOS 12.3.1, seems to be specific to the engine?

**Comment by Inzanit** [comment] 2020-01-19 11:18
I can confirm on the latest stable iOS13.3, this is no longer an issue for me. I'll close this out for now as I haven't seen a complaint for a while.

**Comment by Jay-Madden** [comment] 2022-04-12 13:56
This has reappeared for me on iOS 15.4.1

**Comment by patrickklaeren** [comment] 2024-03-26 14:38
Can no longer replicate on iOS 17.

**Closed by patrickklaeren** 2024-03-26 14:38 UTC
Labels: bug, needs investigation
